### ISSUE TITLE
upstream token is not valid across different project, make it editable only when present

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/betelgeuse#103]
Check is upstream token is present and only if when present edit it. Not all projects have the upstream field.

```
# betelgeuse test-case --path /export/test RHDS --collect-only
Creating test case test_slapd_InstScriptsEnabled for requirement: Setup Ds.
Linking test case test_slapd_InstScriptsEnabled to requirement: Setup Ds.
# betelgeuse test-case --path /export/test RHDS
Password not in config file.
Enter Password:
Creating test case test_slapd_InstScriptsEnabled for requirement: Setup Ds.
Traceback (most recent call last):
  File "/usr/bin/betelgeuse", line 9, in <module>
    load_entry_point('Betelgeuse==0.7.1', 'console_scripts', 'betelgeuse')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/export/betelgeuse/betelgeuse.py", line 649, in test_case
    pool.map(add_test_case, testcases.items())
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
pylarion.exceptions.PylarionLibException: These parameters are unknown: upstream
```

**Comment by elyezer** [comment]
After some more investigation was identified that the upstream field is needed and the project on the devel instance was not updated. With that said this issue can be closed.
