### ISSUE TITLE
Traceback when running betelgeuse for insights tests

### ISSUE THREAD

**Issue by patchkez** [SatelliteQE/betelgeuse#122]
Hi guys,
we are running betelgeuse in our Jenkins pipeline and we are facing this issue recently:
```
Traceback (most recent call last):
  File "venv_polarion/bin/betelgeuse", line 10, in <module>
    sys.exit(cli())
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/betelgeuse/__init__.py", line 669, in test_run
    *collector.collect_tests(source_code_path).values()):
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/betelgeuse/collector.py", line 133, in collect_tests
    tests[path] = _get_tests(path)
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/betelgeuse/collector.py", line 109, in _get_tests
    subnode.name.startswith('test_')
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/betelgeuse/collector.py", line 66, in __init__
    self._parse_docstring()
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/betelgeuse/collector.py", line 86, in _parse_docstring
    self.fields.update(parse_docstring(docstring))
  File "/var/lib/jenkins/workspace/CI-PR-insights-core/insights-tests/venv_polarion/lib/python2.7/site-packages/betelgeuse/parser.py", line 167, in parse_docstring
    document = minidom.parseString(parsed_docstring)
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1931, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 31, column 43
```

I did some investigation and it seems to me is there is some formatting problem with some test docstring. Is there any way how to enable debugging to see which test case is problematic? Can you help me troubleshoot this further please?

**Comment by mirekdlugosz** [comment]
Unfortunately no, betelgeuse does not have any debug mode available...

Is your test case repository public? Or internal to Red Hat? In latter case, can you send me a link? My LDAP id is `mzalewsk`.

It's not revolutionary idea, but I would first try to reproduce problem globally, and then set breakpoint in `betelgeuse/parser.py` line 167, to identify test case that causes this exception. Probably it is malformed and small change to docstring will fix the problem.

**Comment by patchkez** [comment]
@mirzal thank you for your help. Problematic '\b' was removed from docstring and it seems it is working again.
