### ISSUE TITLE
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' with Python 3.9

### ISSUE THREAD

**Issue by XiyangDong** [SatelliteQE/betelgeuse#133]
Hello, when running betelgeuse test-run command in python 3.9 I see below traceback:
```
Traceback (most recent call last):

  File "/usr/local/bin/betelgeuse", line 8, in <module>

    sys.exit(cli())

  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__

    return self.main(*args, **kwargs)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func

    return ctx.invoke(f, obj, *args, **kwargs)

  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/betelgeuse/__init__.py", line 789, in test_run

    testsuite = testsuite.getchildren()[0]

AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' 
```
getchildren was deprecated and in 3.9 it was removed from python library.  Please update code.

**Comment by XiyangDong** [comment]
Also another issue related to this line 'testsuite = testsuite.getchildren()[0]'  in https://github.com/SatelliteQE/betelgeuse/blob/master/betelgeuse/__init__.py#L843

We should iterate through testcases in every testsuite instead of only [0], otherwise for junit file like below it won't work:

```
<testsuites>
<testsuite id="1" name="" tests="17" errors="0" failures="0">
<properties>
<property name="polarion-custom-assignee" value="ASSIGNEE"/>
<property name="polarion-custom-jenkinsjobs" value="JENKINSJOBURL"/>
</properties>
<testcase classname="server: ldap_teardown" name="IDM-SSSD-TC: server: ldap_teardown: runtest">
<system-out> Logs: recipes/1/tasks/6/results/1624999312/logs/avc.log recipes/1/tasks/6/results/1624999312/logs/resultoutputfile.log </system-out>
</testcase>
</testsuite>
<testsuite id="2" name="" tests="53" errors="0" failures="18">
<properties>
<property name="polarion-custom-assignee" value="ASSIGNEE"/>
<property name="polarion-custom-jenkinsjobs" value="JENKINSJOBURL"/>
</properties>
<testcase classname="ldap_provider: sudo" name="IDM-SSSD-TC: ldap_provider: sudo: check defaults entry support">
<failure message=""> Logs: recipes/2/tasks/5/results/1624999307/logs/avc.log recipes/2/tasks/5/results/1624999307/logs/resultoutputfile.log </failure>
</testcase>
<testcase classname="ldap_provider: sudo" name="IDM-SSSD-TC: ldap_provider: sudo: verify configuration option support">
<system-out> Logs: recipes/2/tasks/5/results/1624999308/logs/avc.log recipes/2/tasks/5/results/1624999308/logs/resultoutputfile.log </system-out>
.
.
.
```

**Comment by XiyangDong** [comment]
> Also another issue related to this line 'testsuite = testsuite.getchildren()[0]' in https://github.com/SatelliteQE/betelgeuse/blob/master/betelgeuse/__init__.py#L843
> 
> We should iterate through testcases in every testsuite instead of only [0], otherwise for junit file like below it won't work:
> 
> ```
> <testsuites>
> <testsuite id="1" name="" tests="17" errors="0" failures="0">
> <properties>
> <property name="polarion-custom-assignee" value="ASSIGNEE"/>
> <property name="polarion-custom-jenkinsjobs" value="JENKINSJOBURL"/>
> </properties>
> <testcase classname="server: ldap_teardown" name="IDM-SSSD-TC: server: ldap_teardown: runtest">
> <system-out> Logs: recipes/1/tasks/6/results/1624999312/logs/avc.log recipes/1/tasks/6/results/1624999312/logs/resultoutputfile.log </system-out>
> </testcase>
> </testsuite>
> <testsuite id="2" name="" tests="53" errors="0" failures="18">
> <properties>
> <property name="polarion-custom-assignee" value="ASSIGNEE"/>
> <property name="polarion-custom-jenkinsjobs" value="JENKINSJOBURL"/>
> </properties>
> <testcase classname="ldap_provider: sudo" name="IDM-SSSD-TC: ldap_provider: sudo: check defaults entry support">
> <failure message=""> Logs: recipes/2/tasks/5/results/1624999307/logs/avc.log recipes/2/tasks/5/results/1624999307/logs/resultoutputfile.log </failure>
> </testcase>
> <testcase classname="ldap_provider: sudo" name="IDM-SSSD-TC: ldap_provider: sudo: verify configuration option support">
> <system-out> Logs: recipes/2/tasks/5/results/1624999308/logs/avc.log recipes/2/tasks/5/results/1624999308/logs/resultoutputfile.log </system-out>
> .
> .
> .
> ```

Hello I am still seeing this issue on line https://github.com/SatelliteQE/betelgeuse/blob/master/betelgeuse/__init__.py#L843
Shall we reopen this ticket and fix that?
