### ISSUE TITLE
Skip test case creation for tests with invalid fields values

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/betelgeuse#63]
Test case command should not stop when a invalid value is provided and a `PylarionLibException` is raised.

```
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/bin/betelgeuse", line 11, in <module>
    sys.exit(cli())
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/e79539a1/virtualenvs/d8de43bd/lib/python2.7/site-packages/betelgeuse.py", line 489, in test_case
    pool.map(add_test_case, testcases.items())
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
pylarion.exceptions.PylarionLibException: Acceptable values for testtype are:[functional, nonfunctional, structural]
```

**Comment by elyezer** [comment]
A skip message will be printed and the test case import will continue.
