### ISSUE TITLE
Mark --path and --path-to-source as required fields when using test-run

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#66]
Seems that one needs to pass both `--path` and `--path-to-source` when using `test-run` or Betelgeuse will attempt to open files that were not provided:

``` console
betelgeuse test-run --test-run-id omaciel-delete-1 --test-run-type regression --test-template-id Empty --path /Users/omaciel/Dropbox/xml/tier1-parallel-results.xml --user omaciel --custom-fields arch=x8664 CLOUDTP
Traceback (most recent call last):
  File "/Users/omaciel/.virtualenvs/betelgeuse/bin/betelgeuse", line 9, in <module>
    load_entry_point('Betelgeuse', 'console_scripts', 'betelgeuse')()
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/omaciel/hacking/betelgeuse/betelgeuse.py", line 743, in test_run
    *testimony.get_testcases([source_code_path]).values()
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/site-packages/testimony/__init__.py", line 347, in get_testcases
    if os.path.isfile(path):
  File "/Users/omaciel/.virtualenvs/betelgeuse/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Since [source_code_path](https://github.com/SatelliteQE/betelgeuse/blob/master/betelgeuse.py#L743) is required for a `Test Run`, we should possibly:
- Make sure that the parameter is a requirement
- Consider any other additional checks that we may want to perform to make sure that the provided value matches the expected format (or provide a friendlier message to the end user)

**Comment by elyezer** [comment]
A better approach is to make then a argument instead of a option. By definition an option is optional so an argument is better suited.

**Comment by elyezer** [comment]
This is going to be a breaking change. I will remove from the current milestone and will add back or to a new one if needed.

An option can not be required, an argument should be used for that instead.

**Comment by elyezer** [comment]
The test-run command now have the `source_code_path` (equivalent to `--path-to-source`) and `output_path` (equivalent to `--path`) as arguments and therefore they are required. See the usage:

```
Usage: betelgeuse test-run [OPTIONS] JUNIT_PATH SOURCE_CODE_PATH USER PROJECT
                           OUTPUT_PATH
```

With that we can go ahead and close this.
