### ISSUE TITLE
PicklingError while creating a new requirement

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/betelgeuse#81]
Saw the following error happen 4 times in a row while attempting to create a new `HotBackup` Requirement:

``` console
Creating test case test_positive_directory_exists for requirement: HotBackup.
No handlers could be found for logger "suds.client"
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/bin/betelgeuse", line 11, in <module>
    sys.exit(cli())
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/5ba1b881/virtualenvs/d8de43bd/lib/python2.7/site-packages/betelgeuse.py", line 637, in test_case
    pool.map(add_test_case, testcases.items())
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: 'WebFault(u"Server raised fault: 'Not authorized.'",)'. Reason: 'PicklingError("Can't pickle suds.sudsobject.Fault: attribute lookup suds.sudsobject.Fault failed",)'
```

**Comment by omaciel** [comment]
@elyezer can you investigate please? Look at Jenkins job `polarion-test-case/32/console` for more details

**Comment by elyezer** [comment]
That `Not authorized` is an issue that happens from time to time and there is nothing we can do on our end... Need to raise an issue so they can fix.

I will take a look but it should be like the other times I tried when I could not resolve it and just wait for the server to come back working.

**Comment by elyezer** [comment]
That was a temporary issue like happened before. I am going to close this.
